postgres:
    image: postgres:15
    container_name: test_postgres
    ports:
      - '3330:3330'
    restart: always
    environment:
      PGUSER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    volumes:
      - ./temp/compose/postgres:/var/lib/postgresql/data