---
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_schedule_api
    ports:
      - '${POSTGRES_PORT:-6500}:5432'
    restart: always
    environment:
      PGUSER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    volumes:
      - ./temp/compose/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_schedule_api
    restart: always
    ports:
      - "${REDIS_PORT:-6501}:6379"
    volumes:
      - ./temp/compose/redis:/data

  schedule-api:
    build:
      dockerfile: deploy/docker/api.Dockerfile
      context: ../../
      ssh:
        default: $SSH_AUTH_SOCK
    container_name: schedule-api
    ports:
      - "${API_PORT:-6502}:7070"
    volumes:
      - ./temp/compose/api:/data
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      POETRY_VIRTUALENVS_CREATE: false
      PYTHONPATH: "/project/app"
    depends_on:
      - postgres